# 


In [1]:
import numpy as np


In [3]:
my_list = [1,2,3,4,5]
arr =np.array(my_list)

In [5]:
type(arr)

numpy.ndarray

In [13]:
print(arr)

[1 2 3 4 5]


In [15]:
arr.shape


(5,)

In [17]:
# Multi dimentinol array
my_list1 = [1,2,3,4,5]
my_list2 = [2,3,4,5,6]
my_list3 = [9,7,6,8,9]

arr = np.array([my_list1,my_list2,my_list3])

In [18]:
type(arr)


numpy.ndarray

In [19]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [20]:
arr.shape

(3, 5)

In [21]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [22]:
arr = np.array([1,2,3,4,5,6,7,8])


In [23]:
print(arr)

[1 2 3 4 5 6 7 8]


In [24]:
print(arr[6])

7


In [26]:
arr[3]

np.int64(4)

In [27]:
my_list1 = [1,2,3,4,5]
my_list2 = [2,3,4,5,6]
my_list3 = [9,7,6,8,9]

marr = np.array([my_list1,my_list2,my_list3])

In [28]:
print(marr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [29]:
marr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [30]:
marr[0:2,0:3]

array([[1, 2, 3],
       [2, 3, 4]])

In [40]:
print(marr[1:2,1:3])

[[3 4]]


In [49]:
print(marr[1:2,1:4])


[[3 4 5]]


In [56]:
Arangearr = np.arange(0,15,3)

In [58]:
Arangearr

array([ 0,  3,  6,  9, 12])

In [67]:
LinspaceArr = np.linspace(1,100,30)

In [68]:
LinspaceArr


array([  1.        ,   4.4137931 ,   7.82758621,  11.24137931,
        14.65517241,  18.06896552,  21.48275862,  24.89655172,
        28.31034483,  31.72413793,  35.13793103,  38.55172414,
        41.96551724,  45.37931034,  48.79310345,  52.20689655,
        55.62068966,  59.03448276,  62.44827586,  65.86206897,
        69.27586207,  72.68965517,  76.10344828,  79.51724138,
        82.93103448,  86.34482759,  89.75862069,  93.17241379,
        96.5862069 , 100.        ])

In [70]:
arr


array([1, 2, 3, 4, 5, 6, 7, 8])

In [71]:
# Copy function and brodcasting
arr[5:] = 100
arr

array([  1,   2,   3,   4,   5, 100, 100, 100])

In [74]:
arr1 = arr

In [77]:
arr1[5:] = 500

In [79]:
arr1

array([  1,   2,   3,   4,   5, 500, 500, 500])

In [82]:
arr1= arr.copy()

In [86]:
print(arr1)
print(arr)
arr1[5:]= 1000
print(arr1)
print(arr)

[  1   2   3   4   5 500 500 500]
[  1   2   3   4   5 500 500 500]
[   1    2    3    4    5 1000 1000 1000]
[  1   2   3   4   5 500 500 500]


In [87]:
val =2
arr<val


array([ True, False, False, False, False, False, False, False])

In [88]:
arr >val

array([False, False,  True,  True,  True,  True,  True,  True])

In [97]:
np.ones((5,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [99]:
np.random.rand(6)

array([0.34952819, 0.0281343 , 0.52577867, 0.74775872, 0.27070734,
       0.07741061])

In [103]:
np.random.randint(0,80,25).reshape(5,5)

array([[33, 18, 29, 11, 60],
       [18, 34, 65, 54, 20],
       [29, 18, 54, 72, 26],
       [75, 56, 64, 27, 55],
       [60, 17, 57, 69, 39]], dtype=int32)